/* eslint-disable unicorn/no-abusive-eslint-disable */
/* eslint-disable */

declare global {
  declare var __DYE_RESET__: string
  declare var __DYE_COLOR_OFF__: string
  declare var __DYE_BG_OFF__: string
  declare var __DYE_BOLD__: string
  declare var __DYE_BOLD_OFF__: string
  declare var __DYE_DIM__: string
  declare var __DYE_DIM_OFF__: string
  declare var __DYE_ITALIC__: string
  declare var __DYE_ITALIC_OFF__: string
  declare var __DYE_UNDERSCORE__: string
  declare var __DYE_UNDERSCORE_OFF__: string
  declare var __DYE_INVERSE__: string
  declare var __DYE_INVERSE_OFF__: string
  declare var __DYE_HIDDEN__: string
  declare var __DYE_HIDDEN_OFF__: string
  declare var __DYE_CROSSED__: string
  declare var __DYE_CROSSED_OFF__: string
  declare var __DYE_BLACK__: string
  declare var __DYE_BG_BLACK__: string
  declare var __DYE_BLACK_BRIGHT__: string
  declare var __DYE_BG_BLACK_BRIGHT__: string
  declare var __DYE_RED__: string
  declare var __DYE_BG_RED__: string
  declare var __DYE_RED_BRIGHT__: string
  declare var __DYE_BG_RED_BRIGHT__: string
  declare var __DYE_GREEN__: string
  declare var __DYE_BG_GREEN__: string
  declare var __DYE_GREEN_BRIGHT__: string
  declare var __DYE_BG_GREEN_BRIGHT__: string
  declare var __DYE_YELLOW__: string
  declare var __DYE_BG_YELLOW__: string
  declare var __DYE_YELLOW_BRIGHT__: string
  declare var __DYE_BG_YELLOW_BRIGHT__: string
  declare var __DYE_BLUE__: string
  declare var __DYE_BG_BLUE__: string
  declare var __DYE_BLUE_BRIGHT__: string
  declare var __DYE_BG_BLUE_BRIGHT__: string
  declare var __DYE_MAGENTA__: string
  declare var __DYE_BG_MAGENTA__: string
  declare var __DYE_MAGENTA_BRIGHT__: string
  declare var __DYE_BG_MAGENTA_BRIGHT__: string
  declare var __DYE_CYAN__: string
  declare var __DYE_BG_CYAN__: string
  declare var __DYE_CYAN_BRIGHT__: string
  declare var __DYE_BG_CYAN_BRIGHT__: string
  declare var __DYE_WHITE__: string
  declare var __DYE_BG_WHITE__: string
  declare var __DYE_WHITE_BRIGHT__: string
  declare var __DYE_BG_WHITE_BRIGHT__: string
  declare var __DYE_GRAY01__: string
  declare var __DYE_BG_GRAY01__: string
  declare var __DYE_GRAY02__: string
  declare var __DYE_BG_GRAY02__: string
  declare var __DYE_GRAY03__: string
  declare var __DYE_BG_GRAY03__: string
  declare var __DYE_GRAY04__: string
  declare var __DYE_BG_GRAY04__: string
  declare var __DYE_GRAY05__: string
  declare var __DYE_BG_GRAY05__: string
  declare var __DYE_GRAY06__: string
  declare var __DYE_BG_GRAY06__: string
  declare var __DYE_GRAY07__: string
  declare var __DYE_BG_GRAY07__: string
  declare var __DYE_GRAY08__: string
  declare var __DYE_BG_GRAY08__: string
  declare var __DYE_GRAY09__: string
  declare var __DYE_BG_GRAY09__: string
  declare var __DYE_GRAY10__: string
  declare var __DYE_BG_GRAY10__: string
  declare var __DYE_GRAY11__: string
  declare var __DYE_BG_GRAY11__: string
  declare var __DYE_GRAY12__: string
  declare var __DYE_BG_GRAY12__: string
  declare var __DYE_GRAY13__: string
  declare var __DYE_BG_GRAY13__: string
  declare var __DYE_GRAY14__: string
  declare var __DYE_BG_GRAY14__: string
  declare var __DYE_GRAY15__: string
  declare var __DYE_BG_GRAY15__: string
  declare var __DYE_GRAY16__: string
  declare var __DYE_BG_GRAY16__: string
  declare var __DYE_GRAY17__: string
  declare var __DYE_BG_GRAY17__: string
  declare var __DYE_GRAY18__: string
  declare var __DYE_BG_GRAY18__: string
  declare var __DYE_GRAY19__: string
  declare var __DYE_BG_GRAY19__: string
  declare var __DYE_GRAY20__: string
  declare var __DYE_BG_GRAY20__: string
  declare var __DYE_GRAY21__: string
  declare var __DYE_BG_GRAY21__: string
  declare var __DYE_GRAY22__: string
  declare var __DYE_BG_GRAY22__: string
}
export {}
